# Generated by Django 2.2.5 on 2021-01-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_sold',
            name='item_price',
        ),
        migrations.RemoveField(
            model_name='item_sold',
            name='restaurent',
        ),
        migrations.AddField(
            model_name='item_entry',
            name='item_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item_sold',
            name='item_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
